### ISSUE TITLE
Building Docker image for xl-deploy centos

### ISSUE THREAD

**Issue by maiconpeixinho** [xebialabs/xl-docker-images#26]
Hey there, 

I'm getting this issue while trying to build for XL-Deploy specific.

While runing for XL-Release is everything OK.

Help?!

```
./applejack.py build --xl-version 8.6.1 --download-username XXXXX --download-password XXXXX --product xl-deploy --target-os centos --use-cache
🦄 Whee! Let's go!
/Users/maiconpeixinho/DevOps/Via Varejo/xebia-labs/remote-xl-docker/xl-docker-images/applejack/__init__.py:19: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(p.read_text())
Building Docker image for xl-deploy centos
Traceback (most recent call last):
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./applejack.py", line 81, in <module>
    applejack()
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./applejack.py", line 75, in build
    image_id = builder.build_docker_image(target_os)
  File "/Users/maiconpeixinho/DevOps/Via Varejo/xebia-labs/remote-xl-docker/xl-docker-images/applejack/builder.py", line 44, in build_docker_image
    rm=True,
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/docker/api/build.py", line 259, in build
    timeout=timeout,
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/docker/api/client.py", line 194, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/maiconpeixinho/.local/share/virtualenvs/xl-docker-images-qCNxY5hY/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by maiconpeixinho** [comment]
Docker was not running correctly!
