### ISSUE TITLE
keystore type issue

### ISSUE THREAD

**Issue by seekjp** [xebialabs/xl-docker-images#61]
When xlrelease starts it creates a keystore of type jceks as below

echo "... Generating repository keystore"
keytool -genseckey -alias deployit-passsword-key -keyalg aes -keysize 128 -keypass "deployit" -keystore ${APP_HOME}/conf/repository-keystore.jceks -storetype jceks -storepass ${REPOSITORY_KEYSTORE_PASSPHRASE}

but the java has the default keystore type as jks in the java.security file in the jre/lib/security folder for the JDK. So when we enable ssl=true, the container fails to start with below error.

2020-08-14 21:27:16.571 [main] {activemq.broker=embedded-broker} ERROR c.x.xlrelease.XLReleaseServer - Error occurred while starting XL Release
java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:663)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1194)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:334)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:256)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:94)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:282)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:396)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.xebialabs.xlrelease.XLReleaseServer.start(XLReleaseServer.java:378)
        at com.xebialabs.xlrelease.XLReleaseBootstrapper.startServer(XLReleaseBootstrapper.java:108)
        at com.xebialabs.xlrelease.XLReleaseBootstrapper.start(XLReleaseBootstrapper.java:75)
        at com.xebialabs.xlrelease.XLReleaseBootstrapper.main(XLReleaseBootstrapper.java:53)

################################################################################

XL Release Startup failed: Invalid keystore format

################################################################################

2020-08-14 21:27:16.588 [Thread-5] {} INFO  c.x.xlrelease.XLReleaseServer - Shutting down XL Release because the process is being terminated.
2020-08-14 21:27:16.588 [ActiveMQ ShutdownHook] {activemq.broker=embedded-broker} INFO  o.a.activemq.broker.BrokerService - Apache ActiveMQ 5.15.11 (embedded-broker, ID:xl-release-bffcb6b4b-jl9q4-37553-1597440423013-0:1) is shutting down

**Comment by karthiksonti24** [comment]
@seekjp Still you are facing this issue.

**Comment by seekjp** [comment]
Yes when we enable SSL=true. We disabled SSL and it was able to start up fine.

**Comment by karthiksonti24** [comment]
@mayur9991 Can you have a look at this one.

**Comment by mayur9991** [comment]
@seekjp,

> When xlrelease starts it creates a keystore of type jceks as below
>
> echo "... Generating repository keystore"
> keytool -genseckey -alias deployit-passsword-key -keyalg aes -keysize 128 -keypass "deployit" -keystore ${APP_HOME}/conf/repository-keystore.jceks -storetype jceks -storepass ${REPOSITORY_KEYSTORE_PASSPHRASE}

This keystore is generated to store encryption key and not for ssl.

You can find more about exposed environment variables on our documentation site.
https://docs.xebialabs.com/v.9.7/release/docker/docker-environment-variables/

To configure ssl, follow below link
https://docs.xebialabs.com/v.9.7/release/how-to/update-the-xl-release-digital-certificate/#view-the-certificate

You have to provide path for ssl keystore file and required credentials.
```
keystore.path
keystore.password
keystore.keypassword
```
